### ISSUE TITLE
Referências

### ISSUE THREAD

**Issue by lauthjoao** [ja-on1/jogo1#2]

**Comment by boidacarapreta** [comment]
Por favor, assistam a [The Backrooms](https://www.youtube.com/watch?v=H4dGpz6cnHo)!

**Comment by mariahammes** [comment]
Nossa senhora que alitivo a gravação em primeira pessoa mas adorei, dá para
sentir a tensão que eles propõem, levei um susto com o bicho aparecendo no
final do corredor.

Em sex., 3 de mar. de 2023 às 14:22, Ederson Torresini <
***@***.***> escreveu:

**Comment by mariahammes** [comment]
Referenciâs no README
